[package]
name = "rust regex"
version = "0.1.0"
authors = ["Daniel Schmidt <schmidt.d1908@gmail.com>"]

[lib]
name = "rregex"
crate-type = ["staticlib"]

[dependencies]
regex = { version = "0.2.1"}
libc = "0.2.19"

[features]
simd-accel = ["regex/simd-accel"]

